# Generated by Django 5.1.2 on 2026-09-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='agotado',
            field=models.BooleanField(default=False, help_text='Se acabó por hoy: se oculta del menú sin desactivar el producto.'),
        ),
    ]
